package com.tsy.leanote.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tsy.leanote.feature.note.bean.NoteFile;
import com.tsy.leanote.feature.note.bean.Notebook;
import com.tsy.leanote.feature.note.bean.Note;
import com.tsy.leanote.feature.user.bean.UserInfo;

import com.tsy.leanote.greendao.NoteFileDao;
import com.tsy.leanote.greendao.NotebookDao;
import com.tsy.leanote.greendao.NoteDao;
import com.tsy.leanote.greendao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteFileDaoConfig;
    private final DaoConfig notebookDaoConfig;
    private final DaoConfig noteDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final NoteFileDao noteFileDao;
    private final NotebookDao notebookDao;
    private final NoteDao noteDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteFileDaoConfig = daoConfigMap.get(NoteFileDao.class).clone();
        noteFileDaoConfig.initIdentityScope(type);

        notebookDaoConfig = daoConfigMap.get(NotebookDao.class).clone();
        notebookDaoConfig.initIdentityScope(type);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        noteFileDao = new NoteFileDao(noteFileDaoConfig, this);
        notebookDao = new NotebookDao(notebookDaoConfig, this);
        noteDao = new NoteDao(noteDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(NoteFile.class, noteFileDao);
        registerDao(Notebook.class, notebookDao);
        registerDao(Note.class, noteDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        noteFileDaoConfig.clearIdentityScope();
        notebookDaoConfig.clearIdentityScope();
        noteDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public NoteFileDao getNoteFileDao() {
        return noteFileDao;
    }

    public NotebookDao getNotebookDao() {
        return notebookDao;
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
