package com.tsy.leanote.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.tsy.leanote.feature.note.bean.Notebook;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTEBOOK".
*/
public class NotebookDao extends AbstractDao<Notebook, Long> {

    public static final String TABLENAME = "NOTEBOOK";

    /**
     * Properties of entity Notebook.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Notebookid = new Property(1, String.class, "notebookid", false, "NOTEBOOKID");
        public final static Property Uid = new Property(2, String.class, "uid", false, "UID");
        public final static Property Parent_notebookid = new Property(3, String.class, "parent_notebookid", false, "PARENT_NOTEBOOKID");
        public final static Property Seq = new Property(4, int.class, "seq", false, "SEQ");
        public final static Property Title = new Property(5, String.class, "title", false, "TITLE");
        public final static Property Is_blog = new Property(6, boolean.class, "is_blog", false, "IS_BLOG");
        public final static Property Is_deleted = new Property(7, boolean.class, "is_deleted", false, "IS_DELETED");
        public final static Property Created_time = new Property(8, String.class, "created_time", false, "CREATED_TIME");
        public final static Property Updated_time = new Property(9, String.class, "updated_time", false, "UPDATED_TIME");
        public final static Property Usn = new Property(10, int.class, "usn", false, "USN");
    }


    public NotebookDao(DaoConfig config) {
        super(config);
    }
    
    public NotebookDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTEBOOK\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NOTEBOOKID\" TEXT UNIQUE ," + // 1: notebookid
                "\"UID\" TEXT," + // 2: uid
                "\"PARENT_NOTEBOOKID\" TEXT," + // 3: parent_notebookid
                "\"SEQ\" INTEGER NOT NULL ," + // 4: seq
                "\"TITLE\" TEXT," + // 5: title
                "\"IS_BLOG\" INTEGER NOT NULL ," + // 6: is_blog
                "\"IS_DELETED\" INTEGER NOT NULL ," + // 7: is_deleted
                "\"CREATED_TIME\" TEXT," + // 8: created_time
                "\"UPDATED_TIME\" TEXT," + // 9: updated_time
                "\"USN\" INTEGER NOT NULL );"); // 10: usn
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTEBOOK\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Notebook entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String notebookid = entity.getNotebookid();
        if (notebookid != null) {
            stmt.bindString(2, notebookid);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(3, uid);
        }
 
        String parent_notebookid = entity.getParent_notebookid();
        if (parent_notebookid != null) {
            stmt.bindString(4, parent_notebookid);
        }
        stmt.bindLong(5, entity.getSeq());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
        stmt.bindLong(7, entity.getIs_blog() ? 1L: 0L);
        stmt.bindLong(8, entity.getIs_deleted() ? 1L: 0L);
 
        String created_time = entity.getCreated_time();
        if (created_time != null) {
            stmt.bindString(9, created_time);
        }
 
        String updated_time = entity.getUpdated_time();
        if (updated_time != null) {
            stmt.bindString(10, updated_time);
        }
        stmt.bindLong(11, entity.getUsn());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Notebook entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String notebookid = entity.getNotebookid();
        if (notebookid != null) {
            stmt.bindString(2, notebookid);
        }
 
        String uid = entity.getUid();
        if (uid != null) {
            stmt.bindString(3, uid);
        }
 
        String parent_notebookid = entity.getParent_notebookid();
        if (parent_notebookid != null) {
            stmt.bindString(4, parent_notebookid);
        }
        stmt.bindLong(5, entity.getSeq());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(6, title);
        }
        stmt.bindLong(7, entity.getIs_blog() ? 1L: 0L);
        stmt.bindLong(8, entity.getIs_deleted() ? 1L: 0L);
 
        String created_time = entity.getCreated_time();
        if (created_time != null) {
            stmt.bindString(9, created_time);
        }
 
        String updated_time = entity.getUpdated_time();
        if (updated_time != null) {
            stmt.bindString(10, updated_time);
        }
        stmt.bindLong(11, entity.getUsn());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Notebook readEntity(Cursor cursor, int offset) {
        Notebook entity = new Notebook( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // notebookid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // uid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // parent_notebookid
            cursor.getInt(offset + 4), // seq
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // title
            cursor.getShort(offset + 6) != 0, // is_blog
            cursor.getShort(offset + 7) != 0, // is_deleted
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // created_time
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // updated_time
            cursor.getInt(offset + 10) // usn
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Notebook entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNotebookid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setParent_notebookid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSeq(cursor.getInt(offset + 4));
        entity.setTitle(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIs_blog(cursor.getShort(offset + 6) != 0);
        entity.setIs_deleted(cursor.getShort(offset + 7) != 0);
        entity.setCreated_time(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUpdated_time(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setUsn(cursor.getInt(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Notebook entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Notebook entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Notebook entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
